config/routes.rb
Rails.application.routes.draw do

# 【管理者】

  devise_for :admin, skip: [:registrations, :passwords] ,controllers: {
    :sessions => 'admin/sessions',
    :registrations => 'admin/registrations',
  }

  namespace :admin do
    get 'homes' => 'homes#index', as: 'homes'
  	get '/search'=>'search#search'
  	resources :families, only: [:index, :destroy]
    resources :users, only: [:index, :update]
  	resources :foods, only: [:index, :destroy]
  	resources :comments, only: [:index, :destroy]
    resources :homes, only: [:index]
  end

# 【ユーザー】 新規登録・ログイン・ログアウト
  devise_for :users, controllers: {
    sessions: 'public/sessions',
    passwords: 'public/passwords',
    registrations: 'public/registrations',
    invitations: 'devise/invitations'
  }

# 【ユーザー】 ゲストログイン
  devise_scope :user do
    post "/sessions/guest_sign_in" => "public/sessions#guest_sign_in"
    resources :users, only: [:show]
  end

# ルート設定
  root 'public/homes#top'

# 【ユーザー】 ログイン後のリダイレクト先
  authenticated :user do
    root 'public/foods#index', as: :authenticated_root
  end

  scope module: :public do
  	get '/search'=>'search#search'
    # resources :invitations, only: [:new, :edit]
    resources :places, only: [:create, :destroy]
    resources :foods, only: [:index, :new, :edit, :show, :create, :update, :destroy] do
      resources :likes, only: [:create, :destroy]
      resources :comments, only: [:create, :destroy]
      member do
        get 'show/:id', to: 'foods#show', as: 'show_food'
        get 'edit' => 'foods#edit', as: 'edit_food'
      end
    end
    resources :family_users, only: [:destroy]
    resources :families, only: [:new, :edit, :show, :permit, :create, :update, :destroy] do
      member do
        get 'show/:id', to: 'families#show', as: 'show_family'
        get 'new' => 'families#new', as: 'new_family'
        get 'permit' => 'families#permit'
        get 'edit' => 'families#edit', as: 'edit_family'
        patch 'update' => 'families#update', as: :update_families
        delete 'destroy', to: 'families#destroy', as: :delete_families
      end
      resource :memberships, only: %i[index create destroy]
        member do
          delete 'destroy', to: 'memberships#destroy', as: :delete_membership
        end
      resource :family_users, only: %i[index create destroy]
    end

    get "families/:id/memberships" => "families#memberships", as: :memberships

    resources :users, only: [:index, :show, :update, :destroy] do
      member do
        delete 'destroy', to: 'users#destroy'
      end
    end

    get 'show/users/:id', to: 'users#show', as: 'show_user'
    get 'edit/users' => 'users#edit'
    patch 'update/users' => 'users#update', as: :update_users
    get 'quit/users', to: 'users#quit'
    patch 'out', to: 'users#out'
  end
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :user
  belongs_to :food

  def self.search_for(content,method)
    return none if content.blank?
      if method == 'forward'
        Comment.where('body LIKE ?', content + '%')
      elsif method == 'backword'
        Comment.where('body LIKE ?', '%' + content)
      else
        Comment.where('body LIKE ?', '%' + content + '%')
      end
  end

end

app/controllers/admin/comments_controller.rb
class Admin::CommentsController < ApplicationController
  before_action :authenticate_admin!
  before_action :set_comment, only: [:destroy]

  def index
    @comments = Comment.all.page(params[:page]).per(10)
    @all_comments = Comment.order(created_at: :desc)
  end

  def destroy
    if @comment.destroy!
      flash[:alert] = "コメントが削除されました"
    else
      flash[:alert] = "コメントの削除に失敗しました"
    end
    redirect_to admin_comments_path
  end

  private

  def set_comment
    @comment = Comment.find(params[:id])
  end

  def comment_params
    params.require(:comment).permit(:body)
  end
end

app/helpers/admin/comments_helper.rb
module Admin::CommentsHelper
end

app/views/admin/comments/_index.html.erb
<% if params[:content].present? %>
  <h3>コメント 「<span style="color: red;"><%= params[:content] %></span>」 検索結果</h3>
<% end %>
<div class="container">
  <table class="table">
    <thead>
      <tr style="background-color: #EEEEEE;">
        <th>ID</th>
        <th>コメント対象</th>
        <th>投稿者</th>
        <th></th>
        <th>投稿日時</th>
        <th></th>
      </tr>
    </thead>
    <tbody>
      <% comments.order(created_at: :desc).each do |comment| %>
        <tr>
          <td class="info col-xs-1">
            <%= comment.id %>
          </td>
          <td class="text-left">
            <%= comment.food.name %>
          </td>
          <td class="text-left">
            <%= comment.user.name %>
          </td>
          <td class="text-left">
            <%= comment.body %>
          <td class="text-left">
            <%= content_tag(:span, comment.created_at.strftime("%Y年%m月%d日 %H時%M分")) %>
          </td>
          <td class="col-xs-2">
            <%= link_to "削除", admin_comment_path(comment), method: :delete, data: { confirm: '削除します。 よろしいですか？' }, class: "btn btn-danger" %>
          </td>
        </tr>
      <% end %>
    </tbody>
  </table>
  <%= paginate comments %>
</div>

app/views/admin/comments/index.html.erb
<% total_comment_count = @all_comments.count %>
<h3>コメント一覧 <%= "（全 #{total_comment_count} 件）" %></h3>
<div class="container">
  <table class="table">
    <thead>
      <tr style="background-color: #EEEEEE;">
        <th>ID</th>
        <th>コメント対象</th>
        <th>投稿者</th>
        <th></th>
        <th>投稿日時</th>
        <th></th>
      </tr>
    </thead>
    <tbody>
      <% @comments.order(created_at: :desc).each do |comment| %>
        <tr>
          <td class="info col-xs-1">
            <%= comment.id %>
          </td>
          <td class="text-left">
            <%= comment.food.name %>
          </td>
          <td class="text-left">
            <%= comment.user.name %>
          </td>
          <td class="text-left">
            <%= comment.body %>
          <td class="text-left">
            <%= content_tag(:span, comment.created_at.strftime("%Y年%m月%d日 %H時%M分")) %>
          </td>
          <td class="col-xs-2">
            <%= link_to "削除", admin_comment_path(comment), method: :delete, data: { confirm: '削除します。 よろしいですか？' }, class: "btn btn-danger" %>
          </td>
        </tr>
        <%= paginate @comments %>
      <% end %>
    </tbody>
  </table>
</div>
<%= link_to "TOPに戻る", admin_homes_path, class: "btn btn-info ml-1" %>