config/routes.rb
Rails.application.routes.draw do

# 【管理者】

  devise_for :admin, skip: [:registrations, :passwords] ,controllers: {
    :sessions => 'admin/sessions',
    :registrations => 'admin/registrations',
  }

  namespace :admin do
    get 'homes' => 'homes#index', as: 'homes'
  	get '/search'=>'search#search'
  	resources :families, only: [:index, :destroy]
    resources :users, only: [:index, :update]
  	resources :foods, only: [:index, :destroy]
  	resources :comments, only: [:index, :destroy]
    resources :homes, only: [:index]
  end

# 【ユーザー】 新規登録・ログイン・ログアウト
  devise_for :users, controllers: {
    sessions: 'public/sessions',
    passwords: 'public/passwords',
    registrations: 'public/registrations',
    invitations: 'devise/invitations'
  }

# 【ユーザー】 ゲストログイン
  devise_scope :user do
    post "/sessions/guest_sign_in" => "public/sessions#guest_sign_in"
    resources :users, only: [:show]
  end

# ルート設定
  root 'public/homes#top'

# 【ユーザー】 ログイン後のリダイレクト先
  authenticated :user do
    root 'public/foods#index', as: :authenticated_root
  end

  scope module: :public do
  	get '/search'=>'search#search'
    # resources :invitations, only: [:new, :edit]
    resources :places, only: [:create, :destroy]
    resources :foods, only: [:index, :new, :edit, :show, :create, :update, :destroy] do
      resources :likes, only: [:create, :destroy]
      resources :comments, only: [:create, :destroy]
      member do
        get 'show/:id', to: 'foods#show', as: 'show_food'
        get 'edit' => 'foods#edit', as: 'edit_food'
      end
    end
    resources :family_users, only: [:destroy]
    resources :families, only: [:new, :edit, :show, :permit, :create, :update, :destroy] do
      member do
        get 'show/:id', to: 'families#show', as: 'show_family'
        get 'new' => 'families#new', as: 'new_family'
        get 'permit' => 'families#permit'
        get 'edit' => 'families#edit', as: 'edit_family'
        patch 'update' => 'families#update', as: :update_families
        delete 'destroy', to: 'families#destroy', as: :delete_families
      end
      resource :memberships, only: %i[index create destroy]
        member do
          delete 'destroy', to: 'memberships#destroy', as: :delete_membership
        end
      resource :family_users, only: %i[index create destroy]
    end

    get "families/:id/memberships" => "families#memberships", as: :memberships

    resources :users, only: [:index, :show, :update, :destroy] do
      member do
        delete 'destroy', to: 'users#destroy'
      end
    end

    get 'show/users/:id', to: 'users#show', as: 'show_user'
    get 'edit/users' => 'users#edit'
    patch 'update/users' => 'users#update', as: :update_users
    get 'quit/users', to: 'users#quit'
    patch 'out', to: 'users#out'
  end
end

app/controllers/admin/homes_controller.rb
class Admin::HomesController < ApplicationController
  before_action :authenticate_admin!

  def index
    @latest_families = Family.order(created_at: :desc).limit(3)
    @latest_users = User.order(created_at: :desc).limit(3)
    @latest_foods = Food.order(created_at: :desc).limit(3)
    @latest_comments = Comment.order(created_at: :desc).limit(3)

    @all_families = Family.order(created_at: :desc)
    @all_users = User.order(created_at: :desc)
    @all_foods = Food.order(created_at: :desc)
    @all_comments = Comment.order(created_at: :desc)
  end
end

app/helpers/admin/homes_helper.rb
module Admin::HomesHelper
end

app/views/admin/homes/index.html.erb
<div class="container">
  <div class="row">
    <div class="col-md-6 mb-4">
      <div class="card">
        <div class="card-header">
          <h3>グループ <i class="fa-solid fa-house"></i></h3>
          <% total_family_count = @all_families.count %>
          <% display_count = [total_family_count, 3].min %>
          <%= "（全 #{total_family_count} 件のうち最新 #{display_count} 件を表示）" %>
        </div>
        <div class="card-body">
          <% if total_family_count > 0 %>
          <table class="table">
            <thead>
              <tr style="background-color: #EEEEEE;">
                <th>ID</th>
                <th>グループ名</th>
                <th>作成者</th>
                <th>メンバー数</th>
                <th></th>
              </tr>
            </thead>
            <tbody>
              <% @latest_families.each do |family| %>
                <tr>
                  <td class="info col-xs-1">
                    <%= family.id %>
                  </td>
                  <td class="text-left">
                    <%= family.name %>
                  </td>
                  <td class="text-left">
                    <%= family.owner.name %>
                  </td>
                  <td class="text-left">
                    <%= family.family_users.count + 1 %>
                  </td>
                  <td class="col-xs-2">
                    <%= link_to "削除", admin_family_path(family), method: :delete, data: { confirm: '削除します。 よろしいですか？' }, class: "btn btn-danger" %>
                  </td>
                </tr>
              <% end %>
            </tbody>
          </table>
          <% else %>
            <p style="color: red;">レコードがありません</p>
          <% end %>
        </div>
      </div>
    </div>
    <div class="col-md-6 mb-4">
      <div class="card">
        <div class="card-header">
          <h3>ユーザー <i class="fa-solid fa-user"></i></h3>
          <% total_user_count = @all_users.count %>
          <% display_user_count = [total_user_count, 3].min %>
          <%= "（全 #{total_user_count} 件のうち最新 #{display_user_count} 件を表示）" %>
        </div>
        <div class="card-body">
          <% if total_user_count > 0 %>
          <table class="table">
            <thead>
              <tr style="background-color: #EEEEEE;">
                <th>ID</th>
                <th></th>
                <th>ユーザー名</th>
                <th>会員状況</th>
                <th></th>
              </tr>
            </thead>
            <tbody>
              <% @latest_users.each do |user| %>
                <tr>
                  <td class="info col-xs-1">
                    <%= user.id %>
                  </td>
                  <td class="info col-xs-1">
                    <%= image_tag user.get_profile_image, size: "25x25" %>
                  </td>
                  <td class="text-left">
                    <%= user.name %>
                  </td>
                  <td class="col-xs-2">
                    <% if user.is_active == false %>
                      <p class="text-secondary">退会済</p>
                    <% else %>
                      <p class="text-success">有効</p>
                    <% end %>
                  </td>
                  <td class="col-xs-2">
                    <% if user.email != 'guest@example.com' %>
                      <% if user.is_active %>
                        <%= link_to "退会", admin_user_path(user), method: :patch, data: { confirm: '退会します。 よろしいですか？' }, class: "btn btn-danger" %>
                      <% else %>
                        <%= link_to "有効", admin_user_path(user), method: :patch, data: { confirm: '有効にします。 よろしいですか？' }, class: "btn btn-success" %>
                      <% end %>
                    <% end %>
                  </td>
                </tr>
              <% end %>
            </tbody>
          </table>
          <% else %>
            <p style="color: red;">レコードがありません</p>
          <% end %>
        </div>
      </div>
    </div>
  </div>
  <div class="row">
    <div class="col-md-6 mb-4">
      <div class="card">
        <div class="card-header">
          <h3>食品類 <i class="fa-solid fa-utensils"></i></h3>
          <% total_food_count = @all_foods.count %>
          <% display_food_count = [total_food_count, 3].min %>
          <%= "（全 #{total_food_count} 件のうち最新 #{display_food_count} 件を表示）" %>
        </div>
        <div class="card-body">
          <% if total_food_count > 0 %>
          <table class="table">
            <thead>
              <tr style="background-color: #EEEEEE;">
                <th>ID</th>
                <th></th>
                <th>食品類名</th>
                <th>投稿者</th>
                <th></th>
              </tr>
            </thead>
            <tbody>
              <% @latest_foods.each do |food| %>
                <tr>
                  <td class="info col-xs-1">
                    <%= food.id %>
                  </td>
                  <td class="info col-xs-1">
                    <%= image_tag food.get_foods_image, size: "25x25" %>
                  </td>
                  <td class="text-left">
                    <%= food.name %>
                  </td>
                  <td class="text-left">
                    <%= food.user.name %>
                  </td>
                  <td class="col-xs-2">
                    <%= link_to "削除", admin_food_path(food), method: :delete, data: { confirm: '削除します。 よろしいですか？' }, class: "btn btn-danger" %>
                  </td>
                </tr>
              <% end %>
            </tbody>
          </table>
          <% else %>
            <p style="color: red;">レコードがありません</p>
          <% end %>
        </div>
      </div>
    </div>
    <div class="col-md-6 mb-4">
      <div class="card">
        <div class="card-header">
          <h3>コメント <i class="fa-solid fa-comments"></i></h3>
          <% total_comment_count = @all_comments.count %>
          <% display_comment_count = [total_comment_count, 3].min %>
          <%= "（全 #{total_comment_count} 件のうち最新 #{display_comment_count} 件を表示）" %>
        </div>
        <div class="card-body">
          <% if total_comment_count > 0 %>
          <table class="table">
            <thead>
              <tr style="background-color: #EEEEEE;">
                <th>ID</th>
                <th>投稿者</th>
                <th></th>
                <th></th>
              </tr>
            </thead>
            <tbody>
              <% @latest_comments.each do |comment| %>
                <tr>
                  <td class="info col-xs-1">
                    <%= comment.id %>
                  </td>
                  <td class="text-left">
                    <%= comment.user.name %>
                  </td>
                  <td class="text-left">
                    <%= comment.body %>
                  </td>
                  <td class="col-xs-2">
                    <%= link_to "削除", admin_comment_path(comment), method: :delete, data: { confirm: '削除します。 よろしいですか？' }, class: "btn btn-danger" %>
                  </td>
                </tr>
              <% end %>
            </tbody>
          </table>
          <% else %>
            <p style="color: red;">レコードがありません</p>
          <% end %>
        </div>
      </div>
    </div>
  </div>
</div>