config/routes.rb
Rails.application.routes.draw do

# 【管理者】

  devise_for :admin, skip: [:registrations, :passwords] ,controllers: {
    :sessions => 'admin/sessions',
    :registrations => 'admin/registrations',
  }

  namespace :admin do
    get 'homes' => 'homes#index', as: 'homes'
  	get '/search'=>'search#search'
  	resources :families, only: [:index, :destroy]
    resources :users, only: [:index, :update]
  	resources :foods, only: [:index, :destroy]
  	resources :comments, only: [:index, :destroy]
    resources :homes, only: [:index]
  end

# 【ユーザー】 新規登録・ログイン・ログアウト
  devise_for :users, controllers: {
    sessions: 'public/sessions',
    passwords: 'public/passwords',
    registrations: 'public/registrations',
    invitations: 'devise/invitations'
  }

# 【ユーザー】 ゲストログイン
  devise_scope :user do
    post "/sessions/guest_sign_in" => "public/sessions#guest_sign_in"
    resources :users, only: [:show]
  end

# ルート設定
  root 'public/homes#top'

# 【ユーザー】 ログイン後のリダイレクト先
  authenticated :user do
    root 'public/foods#index', as: :authenticated_root
  end

  scope module: :public do
  	get '/search'=>'search#search'
    # resources :invitations, only: [:new, :edit]
    resources :places, only: [:create, :destroy]
    resources :foods, only: [:index, :new, :edit, :show, :create, :update, :destroy] do
      resources :likes, only: [:create, :destroy]
      resources :comments, only: [:create, :destroy]
      member do
        get 'show/:id', to: 'foods#show', as: 'show_food'
        get 'edit' => 'foods#edit', as: 'edit_food'
      end
    end
    resources :family_users, only: [:destroy]
    resources :families, only: [:new, :edit, :show, :permit, :create, :update, :destroy] do
      member do
        get 'show/:id', to: 'families#show', as: 'show_family'
        get 'new' => 'families#new', as: 'new_family'
        get 'permit' => 'families#permit'
        get 'edit' => 'families#edit', as: 'edit_family'
        patch 'update' => 'families#update', as: :update_families
        delete 'destroy', to: 'families#destroy', as: :delete_families
      end
      resource :memberships, only: %i[index create destroy]
        member do
          delete 'destroy', to: 'memberships#destroy', as: :delete_membership
        end
      resource :family_users, only: %i[index create destroy]
    end

    get "families/:id/memberships" => "families#memberships", as: :memberships

    resources :users, only: [:index, :show, :update, :destroy] do
      member do
        delete 'destroy', to: 'users#destroy'
      end
    end

    get 'show/users/:id', to: 'users#show', as: 'show_user'
    get 'edit/users' => 'users#edit'
    patch 'update/users' => 'users#update', as: :update_users
    get 'quit/users', to: 'users#quit'
    patch 'out', to: 'users#out'
  end
end

app/views/layouts/_error_message.html.erb
<% if resource.errors.any? %>
  <div id="error_explanation" class="alert alert-primary" role="alert">
    <h2>
      <%= I18n.t("errors.messages.not_saved",
                 count: resource.errors.count,
                 resource: resource.class.model_name.human.downcase)
       %>
    </h2>
    <ul>
      <% resource.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
    </ul>
  </div>
<% end %>

app/views/layouts/_familysearch.html.erb
      <%= form_with url: search_path, method: :get, local: true, class: "d-flex align-items-center ml-2" do |f| %>
        <%= f.text_field :content, placeholder: "グループ検索", class: "form-control" %>
        <%= button_tag type: "submit", class: "btn btn-outline-secondary ms-2" do %>
          <i class="fa-solid fa-magnifying-glass"></i>
        <% end %>
      <% end %>

app/views/layouts/_flash.html.erb
<% if flash[:notice] %>
       <p class="text-success"><%= flash[:notice] %></p>
<% end %>
<% if flash[:alert] %>
       <p class="text-danger"><%= flash[:alert] %></p>
<% end %>

app/views/layouts/_foodsearch.html.erb
<% if user_signed_in? %>
  <%= form_with url: search_path, method: :get, local: true, class: "d-flex align-items-center ml-2" do |f| %>
    <%= f.text_field :content, placeholder: "食品類検索", class: "form-control" %>
    <%= button_tag type: "submit", class: "btn btn-outline-secondary ms-2" do %>
      <i class="fa-solid fa-magnifying-glass"></i>
    <% end %>
  <% end %>
<% end %>

app/views/layouts/_footer.html.erb
<footer>
  <p class="text-center" style="margin: 30px auto;">© 2023 06 YutaMorimoto</p>
  <div class="d-flex justify-content-center">
    <a href="#" class="mx-1 text-dark"><i class="fab fa-twitter fa-2x"></i></a>
    <a href="#" class="mx-5 text-dark"><i class="fab fa-instagram fa-2x"></i></a>
    <a href="#" class="mx-1 text-dark"><i class="far fa-envelope fa-2x"></i></a>
  </div>


  <!-- モバイル用の固定ボタンを追加 -->
  <div id="mobileFootNav" class="clearfix">
    <% if user_signed_in? && @user.present? %>
  <div class="ftNavBtn"><a href="<%= root_path %>" class="blueButton"><span class="webfontIcon"><i class="fa-solid fa-stop"></i></span><br />トップ</a></div>
    <% unless @user.email == 'guest@example.com' %>
  <div class="ftNavBtn"><a href="<%= show_user_path(current_user) %>" class="blueButton"><span class="webfontIcon"><i class="fa-solid fa-user"></i></span><br />マイページ</a></div>
    <% end %>
  <div class="ftNavBtn"><a href="<%= foods_path(current_user) %>" class="blueButton"><span class="webfontIcon"><i class="fa-solid fa-utensils"></i></span><br />食品類一覧</a></div>
  <div class="ftNavBtn"><a href="<%= new_food_path(current_user) %>" class="blueButton"><span class="webfontIcon"><i class="fa-regular fa-square-plus"></i></span><br />新規投稿</a></div>
    <% if @user.email == 'guest@example.com' %>
      <div class="ftNavBtn">
        <%= link_to destroy_user_session_path, method: :delete, class: 'blueButton' do %>
        <span class="webfontIcon"><i class="fa-solid fa-right-from-bracket"></i></span><br />
          ログアウト
        <% end %>
      </div>
    <% end %>
    <% elsif admin_signed_in? %>
      <div class="ftNavBtn"><a href="<%= admin_families_path %>" class="blueButton"><span class="webfontIcon"><i class="fa-solid fa-house"></i></span><br />グループ</a></div>
      <div class="ftNavBtn"><a href="<%= admin_users_path %>" class="blueButton"><span class="webfontIcon"><i class="fa-solid fa-user"></i></span><br />ユーザー</a></div>
      <div class="ftNavBtn"><a href="<%= admin_foods_path %>" class="blueButton"><span class="webfontIcon"><i class="fa-solid fa-utensils"></i></span><br />食品類</a></div>
      <div class="ftNavBtn"><a href="<%= admin_comments_path %>" class="blueButton"><span class="webfontIcon"><i class="fa-solid fa-comments"></i></span><br />コメント</a></div>
    <% else %>
      <div class="ftNavBtn"><a href="<%= root_path %>" class="blueButton"><span class="webfontIcon"><i class="fa-solid fa-stop"></i></span><br />トップ</a></div>
      <div class="ftNavBtn"><a href="<%= new_user_registration_path %>" class="blueButton"><span class="webfontIcon"><i class="fa-solid fa-user-plus"></i></span><br />新規登録</a></div>
      <div class="ftNavBtn"><a href="<%= new_user_session_path %>" class="blueButton"><span class="webfontIcon"><i class="fa-solid fa-right-to-bracket"></i></span><br />ログイン</a></div>
      <div class="ftNavBtn">
        <%= link_to sessions_guest_sign_in_path, method: :post, class: 'blueButton' do %>
          <span class="webfontIcon"><i class="fa-regular fa-user"></i></span><br />
            簡単ログイン
        <% end %>
      </div>
    <% end %>
  </div>
</footer>

app/views/layouts/_header.html.erb
<header class="shadow-sm">
  <div class="custom-div d-flex justify-content-center align-items-center">
    <div class="flex-fill">
      <%= link_to root_path, class: "header-title navbar-brand" do %>
        <%= image_tag "logo.jpg", alt: "e-Commu", width: 100, height: 40 %>
      <% end %>
    </div>

    <nav class="navbar navbar-expand-lg navbar-light">
      <div class="container">
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNavDropdown" aria-controls="navbarNavDropdown" aria-expanded="false" aria-label="Toggle navigation">
          <span class="navbar-toggler-icon"></span>
        </button>

        <div class="collapse navbar-collapse" id="navbarNavDropdown">
          <% if user_signed_in? && @user.present? %>
            <ul class="navbar-nav ml-auto">
              <li class="nav-item active">
                <% display_name = current_user.nickname.presence || current_user.name.presence || "ゲスト" %>
                <span class="nav-link text-dark">ようこそ
                  <% unless @user.email == 'guest@example.com' %>
                    <%= image_tag @user.get_profile_image, size: "25x25" %>
                  <% end %>
                  <%= display_name %> さん
                </span>
              </li>

              <li class="nav-item">
                <% unless @user.email == 'guest@example.com' %>
                  <%= link_to "マイページ", show_user_path(current_user), class: "btn btn-outline-secondary mx-3 my-1" %>
                <% end %>
              </li>

              <li class="nav-item">
                <%= link_to "食品類一覧", foods_path(current_user), class: 'btn btn-outline-secondary mx-3 my-1' %>
              </li>

              <li class="nav-item">
                <%= link_to "新規投稿", new_food_path(current_user), class: 'btn btn-outline-secondary mx-3 my-1' %>
              </li>

              <li class="nav-item">
                <%= link_to "ログアウト", destroy_user_session_path, method: :delete, class: 'btn btn-outline-secondary mx-3 my-1' %>
              </li>
            </ul>

          <% elsif admin_signed_in? %>
            <ul class="navbar-nav ml-auto">
              <li class="nav-item">
                <%= link_to "グループ一覧", admin_families_path, class: 'btn btn-outline-secondary mx-0 my-3' %>
              </li>

              <li class="nav-item">
                <%= link_to "ユーザー一覧", admin_users_path, class: 'btn btn-outline-secondary mx-0 my-3' %>
              </li>

              <li class="nav-item">
                <%= link_to "食品類一覧", admin_foods_path, class: 'btn btn-outline-secondary mx-0 my-3' %>
              </li>

              <li class="nav-item">
                <%= link_to "コメント一覧", admin_comments_path, class: 'btn btn-outline-secondary mx-0 my-3' %>
              </li>
            </ul>

            <div class="nav-item pull-right">
              <%= render "layouts/search" %>
            </div>

            <%= link_to "ログアウト", destroy_admin_session_path, method: :delete, class: 'btn btn-outline-secondary mx-0 my-3' %>

          <% else %>
            <ul class="navbar-nav ml-auto">
              <li class="nav-item">
                <%= link_to "新規登録", new_user_registration_path, class: 'btn btn-outline-secondary mx-3 my-1' %>
              </li>

              <li class="nav-item">
                <%= link_to "ログイン", new_user_session_path, class: 'btn btn-outline-secondary mx-3 my-1' %>
              </li>

              <li class="nav-item">
                <%= link_to "簡単ログイン", sessions_guest_sign_in_path, method: :post, class: 'btn btn-outline-secondary mx-3 my-1' %>
              </li>
            </ul>
          <% end %>
        </div>
      </div>
    </nav>
  </div>
</header>

app/views/layouts/_search.html.erb
<% if admin_signed_in? %>
  <%= form_with url: admin_search_path, method: :get, local: true do |f| %>
    <div class="row d-flex justify-content-end mt-2 mr-3">
      <div class="col-md-3 p-0">
        <%= f.text_field :content, placeholder: "Search", class: "form-control" %>
      </div>
      <div class="col-md-3 p-0">
        <%= f.select :model, options_for_select({"グループ" => "family", "ユーザー" => "user" , "食品類" => "food" , "コメント" => "comment"}, selected: "family"), {}, class: "form-control" %>
      </div>
      <div class="col-md-3 p-0">
        <%= f.select :method, options_for_select({"前方一致" => "forward", "後方一致" => "backward", "部分一致" => "partial"}, selected: "forward"), {}, class: "form-control" %>
      </div>
      <div class="col-md-2 p-0">
        <%= button_tag type: "submit", class: "btn btn-outline-secondary m-1" do %>
          <i class="fa-solid fa-magnifying-glass"></i>
        <% end %>
      </div>
    </div>
  <% end %>
<% else %>

<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="ja">
  <script src="https://kit.fontawesome.com/6c57885749.js" crossorigin="anonymous"></script>
  <head>
    <title>e-Commu! - フードロス削減のためのコミュニティサイト</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <meta charset="UTF-8" />
    <meta name="viewport" content="width=device-width,initial-scale=1.0">
    <%= stylesheet_pack_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>
  <body>
    <div id="wrapper">
      <%= render "layouts/header"%>
      <main>
        <div class="container">
          <div id="flash">
            <%= render "layouts/flash" %>
          </div>
          <%= yield %>
      </main>
      <%= render "layouts/footer"%>
        </div>
    </div>
  </body>
</html>